FROM python:3.12-slim

WORKDIR /app

COPY api_gateway/requirements.txt api_gateway_requirements.txt
RUN pip install --no-cache-dir -r api_gateway_requirements.txt
RUN pip install --no-cache-dir alembic asyncpg

COPY alembic /app/alembic
COPY alembic.ini /app/alembic.ini

COPY api_gateway /app/api_gateway
COPY worker_service /app/worker_service

CMD ["alembic", "upgrade", "head"]
