apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: procplatf
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      enableServiceLinks: false
      containers:
        - name: order-service
          image: procplatf-order_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            # Системные настройки
            - name: PYTHONPATH
              value: "/app:/app/order_service"

            # Настройки Kafka (из ConfigMap)
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            # Данные для сборки DATABASE_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DB_NAME

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DB_PORT

            # Собираем итоговую строку подключения
            - name: DATABASE_URL
              value: "postgresql+asyncpg://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

          # Проверка, что сервис жив
          livenessProbe:
            httpGet:
              path: /docs # Или другой эндпоинт, который всегда доступен
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          # Проверка, что сервис готов принимать заказы
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: procplatf
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001       # Порт, по которому к сервису обращается Gateway
      targetPort: 8000 # Порт внутри пода
  type: ClusterIP