apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: procplatf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      # ВАЖНО: Отключает системные переменные Kubernetes типа REDIS_PORT=tcp://...
      # Это решает ошибку "Port could not be cast to integer value"
      enableServiceLinks: false

      containers:
      - name: worker
        image: worker-service:latest
        imagePullPolicy: Never

        # Переменные окружения
        env:
          - name: REDIS_PORT
            value: "6379"  # Явно переопределяем порт числом
        envFrom:
        - configMapRef:
            name: order-service-env
        - secretRef:
            name: postgres-secret

        # Лимиты ресурсов (помогают избежать 137 ошибки)
        resources:
          limits:
            memory: "512Mi" # Увеличил лимит, так как Python + Celery прожорливы
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"