apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: procplatf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      enableServiceLinks: false

      containers:
      - name: worker
        image: worker-service:latest
        imagePullPolicy: Never

        env:
          - name: REDIS_PORT
            value: "6379"
        envFrom:
        - configMapRef:
            name: order-service-env
        - secretRef:
            name: postgres-secret

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"